import type { Metadata } from "next";
import {
  Playfair_Display,
  Playfair_Display_SC,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";
import Header from "@/component/layout/Header";
import Footer from "@/component/layout/Footer";

const playfair = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["vietnamese"],
});

const playfair_sc = Playfair_Display_SC({
  weight: ["400", "700", "900"],
  variable: "--font-playfair-display-sc",
  subsets: ["vietnamese"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${playfair_sc.variable} ${jakarta.variable} antialiased`}
      >
        <Header />
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
