import type { Metadata } from "next";
import {
  Playfair_Display,
  Playfair_Display_SC,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "swiper/css";
import "node-waves/dist/waves.css";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import FlyonuiScript from "../components/FlyonuiScript";

const playfair = Playfair_Display({
  variable: "--title",
  subsets: ["vietnamese"],
});

const playfair_sc = Playfair_Display_SC({
  weight: ["400", "700", "900"],
  variable: "--cta",
  subsets: ["vietnamese"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--body",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="opera">
      <body
        className={`${playfair.variable} ${playfair_sc.variable} ${jakarta.variable} antialiased`}
      >
        <FlyonuiScript />
        <Header />
        <>{children}</>
        <Footer />
        {/* <Script type="text/javascript" src="/node-waves/dist/waves.js"></Script> */}
      </body>
    </html>
  );
}
